# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

project_name: vand

before:
  hooks:
  - go mod tidy
  - npm --prefix ./frontend install
  - npm --prefix ./frontend run-script build

builds:
- env:
  - CGO_ENABLED=0

  main: ./cmd

  tags:
  - embed_frontend

  goos:
  - linux
  - windows
  - darwin

  goarch:
  - "386"
  - amd64
  - arm
  - arm64

  goarm:
  - "7"

archives:
- format: tar.gz
  replacements:
    386: i386
    amd64: x86_64

  files:
  - LICENSE
  - etc/vand.yaml
  - etc/systemd/vand@.service
  - etc/systemd/vand.target

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
