// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: modem.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModemState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wwan            *ModemState_WWAN     `protobuf:"bytes,1,opt,name=wwan,proto3" json:"wwan,omitempty"`
	Wifi            *ModemState_Wifi     `protobuf:"bytes,2,opt,name=wifi,proto3" json:"wifi,omitempty"`
	Ethernet        *ModemState_Ethernet `protobuf:"bytes,3,opt,name=ethernet,proto3" json:"ethernet,omitempty"`
	Power           *ModemState_Power    `protobuf:"bytes,4,opt,name=power,proto3" json:"power,omitempty"`
	SerialNumber    string               `protobuf:"bytes,5,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	DataTransferred uint64               `protobuf:"varint,6,opt,name=data_transferred,json=dataTransferred,proto3" json:"data_transferred,omitempty"`
}

func (x *ModemState) Reset() {
	*x = ModemState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModemState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModemState) ProtoMessage() {}

func (x *ModemState) ProtoReflect() protoreflect.Message {
	mi := &file_modem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModemState.ProtoReflect.Descriptor instead.
func (*ModemState) Descriptor() ([]byte, []int) {
	return file_modem_proto_rawDescGZIP(), []int{0}
}

func (x *ModemState) GetWwan() *ModemState_WWAN {
	if x != nil {
		return x.Wwan
	}
	return nil
}

func (x *ModemState) GetWifi() *ModemState_Wifi {
	if x != nil {
		return x.Wifi
	}
	return nil
}

func (x *ModemState) GetEthernet() *ModemState_Ethernet {
	if x != nil {
		return x.Ethernet
	}
	return nil
}

func (x *ModemState) GetPower() *ModemState_Power {
	if x != nil {
		return x.Power
	}
	return nil
}

func (x *ModemState) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *ModemState) GetDataTransferred() uint64 {
	if x != nil {
		return x.DataTransferred
	}
	return 0
}

type ModemState_WWAN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator        string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	ConnectionText  string `protobuf:"bytes,2,opt,name=connection_text,json=connectionText,proto3" json:"connection_text,omitempty"`
	RegisterNetwork string `protobuf:"bytes,3,opt,name=register_network,json=registerNetwork,proto3" json:"register_network,omitempty"`
	RxLevel         int32  `protobuf:"varint,4,opt,name=rx_level,json=rxLevel,proto3" json:"rx_level,omitempty"`
	TxLevel         int32  `protobuf:"varint,5,opt,name=tx_level,json=txLevel,proto3" json:"tx_level,omitempty"`
	Roaming         bool   `protobuf:"varint,6,opt,name=roaming,proto3" json:"roaming,omitempty"`
	Ipv4            string `protobuf:"bytes,7,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	Ipv6            string `protobuf:"bytes,8,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Mtu             uint32 `protobuf:"varint,9,opt,name=mtu,proto3" json:"mtu,omitempty"`
	RadioQuality    uint32 `protobuf:"varint,10,opt,name=radio_quality,json=radioQuality,proto3" json:"radio_quality,omitempty"`
	Imsi            string `protobuf:"bytes,11,opt,name=imsi,proto3" json:"imsi,omitempty"`
	Imei            string `protobuf:"bytes,12,opt,name=imei,proto3" json:"imei,omitempty"`
}

func (x *ModemState_WWAN) Reset() {
	*x = ModemState_WWAN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModemState_WWAN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModemState_WWAN) ProtoMessage() {}

func (x *ModemState_WWAN) ProtoReflect() protoreflect.Message {
	mi := &file_modem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModemState_WWAN.ProtoReflect.Descriptor instead.
func (*ModemState_WWAN) Descriptor() ([]byte, []int) {
	return file_modem_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ModemState_WWAN) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ModemState_WWAN) GetConnectionText() string {
	if x != nil {
		return x.ConnectionText
	}
	return ""
}

func (x *ModemState_WWAN) GetRegisterNetwork() string {
	if x != nil {
		return x.RegisterNetwork
	}
	return ""
}

func (x *ModemState_WWAN) GetRxLevel() int32 {
	if x != nil {
		return x.RxLevel
	}
	return 0
}

func (x *ModemState_WWAN) GetTxLevel() int32 {
	if x != nil {
		return x.TxLevel
	}
	return 0
}

func (x *ModemState_WWAN) GetRoaming() bool {
	if x != nil {
		return x.Roaming
	}
	return false
}

func (x *ModemState_WWAN) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *ModemState_WWAN) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

func (x *ModemState_WWAN) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *ModemState_WWAN) GetRadioQuality() uint32 {
	if x != nil {
		return x.RadioQuality
	}
	return 0
}

func (x *ModemState_WWAN) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

func (x *ModemState_WWAN) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

type ModemState_Wifi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModemState_Wifi) Reset() {
	*x = ModemState_Wifi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModemState_Wifi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModemState_Wifi) ProtoMessage() {}

func (x *ModemState_Wifi) ProtoReflect() protoreflect.Message {
	mi := &file_modem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModemState_Wifi.ProtoReflect.Descriptor instead.
func (*ModemState_Wifi) Descriptor() ([]byte, []int) {
	return file_modem_proto_rawDescGZIP(), []int{0, 1}
}

type ModemState_Ethernet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModemState_Ethernet) Reset() {
	*x = ModemState_Ethernet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modem_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModemState_Ethernet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModemState_Ethernet) ProtoMessage() {}

func (x *ModemState_Ethernet) ProtoReflect() protoreflect.Message {
	mi := &file_modem_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModemState_Ethernet.ProtoReflect.Descriptor instead.
func (*ModemState_Ethernet) Descriptor() ([]byte, []int) {
	return file_modem_proto_rawDescGZIP(), []int{0, 2}
}

type ModemState_Power struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModemState_Power) Reset() {
	*x = ModemState_Power{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modem_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModemState_Power) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModemState_Power) ProtoMessage() {}

func (x *ModemState_Power) ProtoReflect() protoreflect.Message {
	mi := &file_modem_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModemState_Power.ProtoReflect.Descriptor instead.
func (*ModemState_Power) Descriptor() ([]byte, []int) {
	return file_modem_proto_rawDescGZIP(), []int{0, 3}
}

type ModemState_WWAN_Network struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mcc     uint32 `protobuf:"varint,1,opt,name=mcc,proto3" json:"mcc,omitempty"`
	Mnc     uint32 `protobuf:"varint,2,opt,name=mnc,proto3" json:"mnc,omitempty"`
	Lac     uint32 `protobuf:"varint,3,opt,name=lac,proto3" json:"lac,omitempty"`
	Cid     uint32 `protobuf:"varint,4,opt,name=cid,proto3" json:"cid,omitempty"`
	Country string `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *ModemState_WWAN_Network) Reset() {
	*x = ModemState_WWAN_Network{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modem_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModemState_WWAN_Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModemState_WWAN_Network) ProtoMessage() {}

func (x *ModemState_WWAN_Network) ProtoReflect() protoreflect.Message {
	mi := &file_modem_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModemState_WWAN_Network.ProtoReflect.Descriptor instead.
func (*ModemState_WWAN_Network) Descriptor() ([]byte, []int) {
	return file_modem_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ModemState_WWAN_Network) GetMcc() uint32 {
	if x != nil {
		return x.Mcc
	}
	return 0
}

func (x *ModemState_WWAN_Network) GetMnc() uint32 {
	if x != nil {
		return x.Mnc
	}
	return 0
}

func (x *ModemState_WWAN_Network) GetLac() uint32 {
	if x != nil {
		return x.Lac
	}
	return 0
}

func (x *ModemState_WWAN_Network) GetCid() uint32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *ModemState_WWAN_Network) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

var File_modem_proto protoreflect.FileDescriptor

var file_modem_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdd, 0x05,
	0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x04,
	0x77, 0x77, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x57, 0x57, 0x41, 0x4e, 0x52, 0x04, 0x77, 0x77,
	0x61, 0x6e, 0x12, 0x24, 0x0a, 0x04, 0x77, 0x69, 0x66, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x57, 0x69,
	0x66, 0x69, 0x52, 0x04, 0x77, 0x69, 0x66, 0x69, 0x12, 0x30, 0x0a, 0x08, 0x65, 0x74, 0x68, 0x65,
	0x72, 0x6e, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x45, 0x74, 0x68, 0x65, 0x72, 0x6e, 0x65, 0x74,
	0x52, 0x08, 0x65, 0x74, 0x68, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x70, 0x6f,
	0x77, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x05, 0x70, 0x6f,
	0x77, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0f, 0x64, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x72, 0x65, 0x64, 0x1a, 0xba, 0x03, 0x0a, 0x04, 0x57, 0x57, 0x41, 0x4e, 0x12, 0x1a, 0x0a, 0x08,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x78,
	0x74, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x19, 0x0a, 0x08,
	0x72, 0x78, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x72, 0x78, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x78, 0x5f, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x78, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x6f, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x70, 0x76, 0x34, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x70, 0x76, 0x34,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x70, 0x76, 0x36, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x69, 0x70, 0x76, 0x36, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74, 0x75, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x61, 0x64, 0x69, 0x6f, 0x5f,
	0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72,
	0x61, 0x64, 0x69, 0x6f, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x6d, 0x73, 0x69, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6d, 0x73, 0x69, 0x12,
	0x12, 0x0a, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69,
	0x6d, 0x65, 0x69, 0x1a, 0x6b, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x63, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x63, 0x63,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d,
	0x6e, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x6c, 0x61, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x1a, 0x06, 0x0a, 0x04, 0x57, 0x69, 0x66, 0x69, 0x1a, 0x0a, 0x0a, 0x08, 0x45, 0x74, 0x68, 0x65,
	0x72, 0x6e, 0x65, 0x74, 0x1a, 0x07, 0x0a, 0x05, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x42, 0x1e, 0x5a,
	0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x76, 0x30,
	0x67, 0x2f, 0x76, 0x61, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modem_proto_rawDescOnce sync.Once
	file_modem_proto_rawDescData = file_modem_proto_rawDesc
)

func file_modem_proto_rawDescGZIP() []byte {
	file_modem_proto_rawDescOnce.Do(func() {
		file_modem_proto_rawDescData = protoimpl.X.CompressGZIP(file_modem_proto_rawDescData)
	})
	return file_modem_proto_rawDescData
}

var file_modem_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_modem_proto_goTypes = []interface{}{
	(*ModemState)(nil),              // 0: ModemState
	(*ModemState_WWAN)(nil),         // 1: ModemState.WWAN
	(*ModemState_Wifi)(nil),         // 2: ModemState.Wifi
	(*ModemState_Ethernet)(nil),     // 3: ModemState.Ethernet
	(*ModemState_Power)(nil),        // 4: ModemState.Power
	(*ModemState_WWAN_Network)(nil), // 5: ModemState.WWAN.Network
}
var file_modem_proto_depIdxs = []int32{
	1, // 0: ModemState.wwan:type_name -> ModemState.WWAN
	2, // 1: ModemState.wifi:type_name -> ModemState.Wifi
	3, // 2: ModemState.ethernet:type_name -> ModemState.Ethernet
	4, // 3: ModemState.power:type_name -> ModemState.Power
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_modem_proto_init() }
func file_modem_proto_init() {
	if File_modem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModemState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModemState_WWAN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModemState_Wifi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modem_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModemState_Ethernet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modem_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModemState_Power); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modem_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModemState_WWAN_Network); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modem_proto_goTypes,
		DependencyIndexes: file_modem_proto_depIdxs,
		MessageInfos:      file_modem_proto_msgTypes,
	}.Build()
	File_modem_proto = out.File
	file_modem_proto_rawDesc = nil
	file_modem_proto_goTypes = nil
	file_modem_proto_depIdxs = nil
}
