// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: vand.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Timestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seconds     uint32 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanoseconds uint32 `protobuf:"varint,2,opt,name=nanoseconds,proto3" json:"nanoseconds,omitempty"`
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_vand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_vand_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetSeconds() uint32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanoseconds() uint32 {
	if x != nil {
		return x.Nanoseconds
	}
	return 0
}

type StateUpdatePoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *Timestamp        `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Solar     *SolarState       `protobuf:"bytes,2,opt,name=solar,proto3" json:"solar,omitempty"`
	Bat       *BatteryState     `protobuf:"bytes,3,opt,name=bat,proto3" json:"bat,omitempty"`
	Gps       *GpsState         `protobuf:"bytes,4,opt,name=gps,proto3" json:"gps,omitempty"`
	Car       *CarOBD2State     `protobuf:"bytes,5,opt,name=car,proto3" json:"car,omitempty"`
	Env       *EnvironmentState `protobuf:"bytes,6,opt,name=env,proto3" json:"env,omitempty"`
	Modem     *ModemState       `protobuf:"bytes,7,opt,name=modem,proto3" json:"modem,omitempty"`
}

func (x *StateUpdatePoint) Reset() {
	*x = StateUpdatePoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vand_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateUpdatePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdatePoint) ProtoMessage() {}

func (x *StateUpdatePoint) ProtoReflect() protoreflect.Message {
	mi := &file_vand_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdatePoint.ProtoReflect.Descriptor instead.
func (*StateUpdatePoint) Descriptor() ([]byte, []int) {
	return file_vand_proto_rawDescGZIP(), []int{1}
}

func (x *StateUpdatePoint) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StateUpdatePoint) GetSolar() *SolarState {
	if x != nil {
		return x.Solar
	}
	return nil
}

func (x *StateUpdatePoint) GetBat() *BatteryState {
	if x != nil {
		return x.Bat
	}
	return nil
}

func (x *StateUpdatePoint) GetGps() *GpsState {
	if x != nil {
		return x.Gps
	}
	return nil
}

func (x *StateUpdatePoint) GetCar() *CarOBD2State {
	if x != nil {
		return x.Car
	}
	return nil
}

func (x *StateUpdatePoint) GetEnv() *EnvironmentState {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StateUpdatePoint) GetModem() *ModemState {
	if x != nil {
		return x.Modem
	}
	return nil
}

type StateUpdateMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points []*StateUpdatePoint `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
}

func (x *StateUpdateMessage) Reset() {
	*x = StateUpdateMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vand_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateUpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateUpdateMessage) ProtoMessage() {}

func (x *StateUpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vand_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateUpdateMessage.ProtoReflect.Descriptor instead.
func (*StateUpdateMessage) Descriptor() ([]byte, []int) {
	return file_vand_proto_rawDescGZIP(), []int{2}
}

func (x *StateUpdateMessage) GetPoints() []*StateUpdatePoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusUpdate *StateUpdateMessage `protobuf:"bytes,1,opt,name=status_update,json=statusUpdate,proto3" json:"status_update,omitempty"`
	Signature    []byte              `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vand_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_vand_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_vand_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetStatusUpdate() *StateUpdateMessage {
	if x != nil {
		return x.StatusUpdate
	}
	return nil
}

func (x *Message) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_vand_proto protoreflect.FileDescriptor

var file_vand_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x76, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x73, 0x6f,
	0x6c, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x62, 0x61, 0x74, 0x74, 0x65,
	0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x67, 0x70, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x6f, 0x62, 0x64, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x11, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x47, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6e, 0x61, 0x6e,
	0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x86, 0x02, 0x0a, 0x10, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x28, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x21, 0x0a, 0x05, 0x73, 0x6f, 0x6c, 0x61, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x53, 0x6f, 0x6c, 0x61, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x6f, 0x6c, 0x61, 0x72, 0x12, 0x1f, 0x0a, 0x03, 0x62, 0x61,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x65, 0x72,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x03, 0x62, 0x61, 0x74, 0x12, 0x1b, 0x0a, 0x03, 0x67,
	0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x47, 0x70, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x03, 0x67, 0x70, 0x73, 0x12, 0x1f, 0x0a, 0x03, 0x63, 0x61, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x43, 0x61, 0x72, 0x4f, 0x42, 0x44, 0x32, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x03, 0x63, 0x61, 0x72, 0x12, 0x23, 0x0a, 0x03, 0x65, 0x6e, 0x76,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x21,
	0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x4d, 0x6f, 0x64, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6d, 0x22, 0x3f, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x22, 0x61, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a,
	0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x76, 0x30, 0x67, 0x2f, 0x76, 0x61, 0x6e, 0x64, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vand_proto_rawDescOnce sync.Once
	file_vand_proto_rawDescData = file_vand_proto_rawDesc
)

func file_vand_proto_rawDescGZIP() []byte {
	file_vand_proto_rawDescOnce.Do(func() {
		file_vand_proto_rawDescData = protoimpl.X.CompressGZIP(file_vand_proto_rawDescData)
	})
	return file_vand_proto_rawDescData
}

var file_vand_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vand_proto_goTypes = []interface{}{
	(*Timestamp)(nil),          // 0: Timestamp
	(*StateUpdatePoint)(nil),   // 1: StateUpdatePoint
	(*StateUpdateMessage)(nil), // 2: StateUpdateMessage
	(*Message)(nil),            // 3: Message
	(*SolarState)(nil),         // 4: SolarState
	(*BatteryState)(nil),       // 5: BatteryState
	(*GpsState)(nil),           // 6: GpsState
	(*CarOBD2State)(nil),       // 7: CarOBD2State
	(*EnvironmentState)(nil),   // 8: EnvironmentState
	(*ModemState)(nil),         // 9: ModemState
}
var file_vand_proto_depIdxs = []int32{
	0, // 0: StateUpdatePoint.timestamp:type_name -> Timestamp
	4, // 1: StateUpdatePoint.solar:type_name -> SolarState
	5, // 2: StateUpdatePoint.bat:type_name -> BatteryState
	6, // 3: StateUpdatePoint.gps:type_name -> GpsState
	7, // 4: StateUpdatePoint.car:type_name -> CarOBD2State
	8, // 5: StateUpdatePoint.env:type_name -> EnvironmentState
	9, // 6: StateUpdatePoint.modem:type_name -> ModemState
	1, // 7: StateUpdateMessage.points:type_name -> StateUpdatePoint
	2, // 8: Message.status_update:type_name -> StateUpdateMessage
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_vand_proto_init() }
func file_vand_proto_init() {
	if File_vand_proto != nil {
		return
	}
	file_solar_proto_init()
	file_battery_proto_init()
	file_gps_proto_init()
	file_obd2_proto_init()
	file_environment_proto_init()
	file_modem_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_vand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vand_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateUpdatePoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vand_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateUpdateMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vand_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vand_proto_goTypes,
		DependencyIndexes: file_vand_proto_depIdxs,
		MessageInfos:      file_vand_proto_msgTypes,
	}.Build()
	File_vand_proto = out.File
	file_vand_proto_rawDesc = nil
	file_vand_proto_goTypes = nil
	file_vand_proto_depIdxs = nil
}
