# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Build

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y protobuf-compiler make

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install build and test dependencies
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        npm --prefix frontend install

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --timeout=10m

    - name: Build code
      run: |
        make frontend
        make backend
